# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d5be25cb23c61fbf1838b0648bf667f1309b21a02ba5ceaddd4a8b0bfa396d5581b683824cb144259ba702499a039b1c6481dd6a21dddf4fb2ee549dd025b9d

test:
  secret_key_base: a702c0bb71cbe23ae383e66a67880cc65d5e1682fec9b0cf7706f34e9e503598bdc15768005b261f7a7a5bac65309d412013a166fd656906dd6a70fb1261df62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
